let fruits=['apple','banana','mango','papaya'];
console.log("before applying array methods fruits are:",fruits);
fruits.push("pineapple");
console.log("After push fruits are:",fruits);
fruits.pop();
console.log("After pop fruits are:",fruits);
fruits.unshift("kiwi");
console.log("After unshift fruits are:",fruits);
fruits.shift();
console.log("After shift fruits are:",fruits);
